name: loyla_delivery
description: "Loyla Delivery app for couriers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  google_fonts: ^6.3.3
  video_player: ^2.9.0
  curved_navigation_bar: ^1.0.6
  font_awesome_flutter: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - assets/videos/